files:
  - source: /_locales/en/messages.json
    translation: /_locales/%two_letters_code%/%original_file_name%
    update_option: update_without_changes
    languages_mapping:
      two_letters_code:
        zh-CN: zh_CN
        zh-TW: zh_TW
        pt-PT: pt_PT
        pt-BR: pt_BR
        es-419: es_419
